DL-13364 - Added basic page and controller
hmrc/ated-frontend pull request #441
Opened 2024-08-08 15:45 UTC by nehakannaujia1

# JIRA Story or Github Number - descriptive title

**Bug fix / New feature** (delete as appropriate)

Please include a summary / description of the change and which issue it fixes.  Include any relevant user needs, context or links to other PRs related to this PR (eg. acceptance tests, environment config).

## Checklist

*Reviewee* (Replace with your name)
 - [x]  I've made every effort to commit high quality, clean code and I have executed relevant static analyses to be sure
 - [x]  I've included appropriate tests with any code I've added (Unit, Integration, Acceptance etc.)
 - [x]  I've executed the acceptance test pack locally to ensure there are no functional regressions
 - [x]  I've added my code using logical, atomic commits, squashing as appropriate - including the JIRA issue number in the commit message
 - [ ]  I've run a dependency check to ensure all dependencies are up to date

*Reviewer* (Replace with your name)
 - [ ]  I've confirmed that every effort has been made to commit high quality, clean code and I have executed relevant static analyses to be sure
 - [ ]  I've confirmed appropriate tests has been included with any code added (Unit, Integration, Acceptance etc.)
 - [ ]  I've executed the acceptance test pack locally to ensure there are no functional regressions
 - [ ]  I've confirmed code was added using logical, atomic commits, squashing as appropriate - including the JIRA issue number in the commit message
 - [ ]  I've run a dependency check to ensure all dependencies are up to date

2024-08-09 13:13 UTC, nehakannaujia1 commented
Apologies , I deleted it accidentally, bringing in for review again.

2024-08-13 13:30 UTC, benryan1790 requested changes

2024-08-13 13:30 UTC, benryan1790 commented on app/controllers/propertyDetails/PropertyDetailsExitController.scala
> +  implicit lazy val messages: Messages = MessagesImpl(mcc.langs.availables.head, messagesApi)
This line is unnecessary, the template already has access to an implicit messages so we can remove this line of code

2024-08-13 13:30 UTC, benryan1790 commented on app/controllers/propertyDetails/PropertyDetailsExitController.scala
> +    authAction.authorisedAction { implicit authContext =>
We should add in the check of the newRevaluedFeature flag in the config like we did in DL-13360, to ensure that users cannot mistakenly access this page before we are ready (should wait until DL-13360 is merged)

2024-08-23 08:27 UTC, merged