DL-13370: Tidy up task
hmrc/ated-frontend pull request #456
Opened 2024-11-25 08:55 UTC by Byasar3

# JIRA Story or Github Number - descriptive title

**Bug fix / New feature** (delete as appropriate)

Please include a summary / description of the change and which issue it fixes.  Include any relevant user needs, context or links to other PRs related to this PR (eg. acceptance tests, environment config).

## Checklist

*Reviewee* (Replace with your name)
 - [ ]  I've made every effort to commit high quality, clean code and I have executed relevant static analyses to be sure
 - [ ]  I've included appropriate tests with any code I've added (Unit, Integration, Acceptance etc.)
 - [ ]  I've executed the acceptance test pack locally to ensure there are no functional regressions
 - [ ]  I've added my code using logical, atomic commits, squashing as appropriate - including the JIRA issue number in the commit message
 - [ ]  I've run a dependency check to ensure all dependencies are up to date

*Reviewer* (Replace with your name)
 - [ ]  I've confirmed that every effort has been made to commit high quality, clean code and I have executed relevant static analyses to be sure
 - [ ]  I've confirmed appropriate tests has been included with any code added (Unit, Integration, Acceptance etc.)
 - [ ]  I've executed the acceptance test pack locally to ensure there are no functional regressions
 - [ ]  I've confirmed code was added using logical, atomic commits, squashing as appropriate - including the JIRA issue number in the commit message
 - [ ]  I've run a dependency check to ensure all dependencies are up to date

2024-11-25 23:02 UTC, christianmennerich requested changes
`ApplicationConfig`  still has the value `newRevaluedFeature`, that is used in `PropertyDetailsExitController`. But the key `revaluedNewJourney` does not exist any more. The behaviour of the controller needs to be fixed.

Needs rebase to `main`.

Some dependencies can be updated.

2024-11-26 12:57 UTC, Byasar3 commented on app/forms/PropertyDetailsForms.scala
>    //scalastyle:off cyclomatic.complexity
removed :+1:

2024-11-26 13:00 UTC, Byasar3 commented on app/utils/AtedConstants.scala
> -  val Change: String = "C"
those set of constants look related, so i've removed the extra blank line between them. There are also unused constants in this file, shall I remove those too?
`  val IdentifierUtr: String = "utr"
  val LoggedInUser: String = "loggedInUser"
  val PeriodKey: String = "2015"
`
i don't see any use of them within the repo

2024-11-29 18:07 UTC, christianmennerich approved these changes

2024-12-02 12:36 UTC, merged